config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  get 'sign_up' => "users#new"
  root "signin#index"
  get 'sign_in' => "signin#index"
  post "sign_in" => "signin#create"
  get "sign_out" => "signin#destroy"

  resources :users, :path => '' do
    resources :contexts
  end



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord

  has_many :articles
  has_many :users_informations

  attr_accessor :password
  before_save :encrypt_password
  #驗證兩個字段是否相等
  validates_confirmation_of :password

  #檢查資料為非 nil 或空字串
  validates_presence_of :password, :on => :create
  validates_presence_of :username
  # validates_presence_of :email

  #檢查資料在資料表中必須唯一
  validates_uniqueness_of :username
  # validates_uniqueness_of :email

  def self.authenticate(username, password)
    user = find_by_username(username)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end

  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :is_public_private, only: [:edit, :update, :show]
  layout "log_in", :only => [:new, :create]

  def new
    @user = User.new
    @page_title = "註冊"
  end

  def create
    @page_title = "註冊"
    @user = User.new(user_params)
    if @user.save
      UsersInformation.create(:email => @user.email, :user_id => @user.id)
      Article.create(:user_id => @user.id, :title => "歡迎～", :author => "admin", :tag => "你的第一篇", :pentime => Time.zone.now, :context => "這是您的第一篇文章")
      redirect_to root_url, :notice => "註冊成功"
    else
      flash.now.alert = "註冊失敗"
      render "new"
    end
  end

  def edit
    if @public_page_user.nil?
      # 網址資料錯誤
      redirect_to root_path
    else
      if session[:user_id].nil?
        # 未登入
        redirect_to root_path
      else
        # 已登入
        if session[:user_id] == @public_page_user.id
          @public_page_user = nil
          @userInformation = UsersInformation.find_by_user_id(session[:user_id])
          @article_size = Article.where(:user_id => session[:user_id] ).count
        else
          redirect_to edit_user_path(@private_page_user.username)
        end
      end
    end
  end

  def update
    if @public_page_user.nil?
      # 網址資料錯誤
      redirect_to root_path
    else
      if session[:user_id].nil?
        # 未登入
        redirect_to root_path
      else
        if session[:user_id] == @public_page_user.id
          @public_page_user = nil
          userInformation = UsersInformation.find_by_user_id(session[:user_id])
          if userInformation.update(users_informations_params)
            redirect_to edit_user_path(@private_user.username)
          else
            render :edit
          end
        else
          redirect_to edit_user_path(@private_user.username)
        end
      end
    end
  end

  def show
    if @public_page_user.nil?
      # 網址資料錯誤
      redirect_to root_path
    else
      @article_size = Article.where(:user_id => @public_page_user.id ).count
      @userInformation = UsersInformation.find_by_user_id(@public_page_user.id)
      if session[:user_id].nil?
        # 未登入
      else
        # 已登入
        if @public_page_user.id != session[:user_id]
          # 登入訪問別人
        elsif @public_page_user.id == session[:user_id]
          # 登入訪問自己
          @public_page_user = nil
        end
      end
      @page_title = @userInformation.name
    end
  end


  private

  def user_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end

  def users_informations_params
    params.require(:users_information).permit(:name, :email, :birthday, :school, :github, :facebook, :twitter, :instagram, :image, :header_image, :about)
  end

  def is_public_private
    @public_page_user = User.find_by_username(params[:id])
    @private_page_user = User.find_by_id(session[:user_id])
    if @public_page_user.present?
      @common＿lock = @public_page_user
    else
      @common＿lock = @private_page_user
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div class="row">
  <div class="col-xl-4 order-xl-2 mb-5 mb-xl-0">
    <div class="card card-profile shadow">
      <div class="row justify-content-center">
        <div class="col-lg-3 order-lg-2">
          <div class="card-profile-image">
            <!-- <a href="#"> -->
            <% if @userInformation.image.present? %>
              <%= image_tag @userInformation.image_url, :class => "rounded-circle" %>
            <% else %>
              <%= image_tag "penguin.jpg", :class => "rounded-circle" %>
            <% end %>
            <!-- </a> -->
          </div>
        </div>
      </div>
      <div class="card-header text-center border-0 pt-8 pt-md-4 pb-0 pb-md-4">
        <div class="d-flex justify-content-between">
          <!-- <a href="#" class="btn btn-sm btn-info mr-4">Connect</a> -->
          <!-- <a href="#" class="btn btn-sm btn-default float-right">Message</a> -->
        </div>
      </div>
      <div class="card-body pt-0 pt-md-4">
        <div class="row">
          <div class="col">
            <div class="card-profile-stats d-flex justify-content-center mt-md-5">
              <div>
                <span class="heading"><%= @article_size %></span>
                <span class="description">文章</span>
              </div>
              <div>
                <% if @userInformation.email.blank? %>
                  <i class="far fa-3x fa-envelope blank_email"></i>
                <% else %>
                  <%= mail_to @userInformation.email do %>
                    <i class="far fa-3x fa-envelope"></i>
                  <% end %>
                <% end %>
              </div>
              <div>
                <% if @userInformation.twitter.blank? %>
                  <i class="fab fa-3x fa-twitter blank_twitter"></i>
                <% else %>
                  <%= link_to @userInformation.twitter, :target => "_blank" do %>
                    <i class="fab fa-3x fa-twitter"></i>
                  <% end %>
                <% end %>
              </div>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col">
            <div class="card-profile-stats d-flex justify-content-center " style="margin-top:-30px">  <!--增加與上方距離 mt-md-5 -->
              <div>
                <% if @userInformation.github.blank? %>
                  <i class="fab fa-3x fa-github blank_github"></i>
                <% else %>
                  <%= link_to @userInformation.github, :target => "_blank" do %>
                    <i class="fab fa-3x fa-github"></i>
                  <% end %>
                <% end %>
              </div>
              <div>
                <% if @userInformation.facebook.blank? %>
                  <i class="fab fa-3x fa-facebook blank_facebook"></i>
                <% else %>
                  <%= link_to @userInformation.facebook, :target => "_blank" do %>
                    <i class="fab fa-3x fa-facebook-square"></i>
                  <% end %>
                <% end %>
              </div>
              <div>
                <% if @userInformation.instagram.blank? %>
                  <i class="fab fa-3x fa-instagram blank_instagram"></i>
                <% else %>
                  <%= link_to @userInformation.instagram, :target => "_blank" do %>
                    <i class="fab fa-3x fa-instagram"></i>
                  <% end %>
                <% end %>
              </div>
            </div>
          </div>
        </div>
        <div class="text-center">
          <h2>
            <%= @userInformation.name if @userInformation.name.present? %>
          </h2>
          <div class="h5 font-weight-300">
            <i class="ni location_pin mr-2"></i>
            <span class="font-weight-light">
              <%= @userInformation.birthday if @userInformation.birthday.present? %>
            </span>
          </div>
          <!-- <div class="h5 mt-4">
            <i class="ni business_briefcase-24 mr-2"></i>學生
          </div> -->
          <div>
            <i class="ni education_hat mr-2"></i>
            <%= @userInformation.school if @userInformation.school.present? %>
          </div>
          <hr class="my-4" />
          <p>
            <% if @userInformation.about.present? %>
              <%= (truncate(strip_tags(@userInformation.about), length: 100)).html_safe %>
            <% else %>
              <%= "這個人很懶，什麼東西都沒有留下..."%>
            <% end %>
          </p>
          <%= link_to "查看更多...", user_path(@private_page_user.username) %>
        </div>
      </div>
    </div>
  </div>
  <div class="col-xl-8 order-xl-1">
    <div class="card bg-secondary shadow">
      <div class="card-header bg-white border-0">
        <div class="row align-items-center">
          <div class="col-8">
            <h3 class="mb-0">個人資料編輯</h3>
          </div>
          <div class="col-4 text-right">
            <!-- <a href="#!" class="btn btn-sm btn-primary">儲存</a> -->
          </div>
        </div>
      </div>
      <div class="card-body">
        <%= form_with model: @userInformation, url: user_path do |f| %>
          <h6 class="heading-small text-muted mb-4">資訊</h6>
          <div class="pl-lg-4">
            <div class="row">
              <div class="col-lg-6">
                <div class="form-group">
                  <label class="form-control-label" for="input-name">姓名</label>
                  <%= f.text_field :name, :class => "form-control form-control-alternative", :id => "input-name", :placeholder => "姓名", :required => "required" %>
                </div>
              </div>
              <div class="col-lg-6">
                <div class="form-group">
                  <label class="form-control-label" for="input-email">電子郵件</label>
                  <%= f.text_field :email, :class => "form-control form-control-alternative", :id => "input-email", :placeholder => "電子郵件", :required => "required" %>
                </div>
              </div>
            </div>
            <div class="row">
              <div class="col-lg-6">
                <div class="form-group">
                  <label class="form-control-label" for="input-birthday">生日</label>
                  <%= f.text_field :birthday, :class => "form-control form-control-alternative", :id => "input-birthday", :placeholder => "生日", :required => "required" %>
                </div>
              </div>
              <div class="col-lg-6">
                <div class="form-group">
                  <label class="form-control-label" for="input-school">校系</label>
                  <%= f.text_field :school, :class => "form-control form-control-alternative", :id => "input-school",:placeholder => "請輸入學系", :required => "required" %>
                </div>
              </div>
            </div>
          </div>
          <hr class="my-4" />
          <!-- Address -->
          <!-- <h6 class="heading-small text-muted mb-4">地址</h6> -->
          <div class="pl-lg-4">
            <div class="row">
              <div class="col-md-12">
                <div class="form-group">
                  <label class="form-control-label" for="input-Facebook">Facebook網址</label>
                  <%= f.text_field :facebook, :class => "form-control form-control-alternative", :id => "input-Facebook", :placeholder => "請輸入Facebook網址" %>
                </div>
              </div>
              <div class="col-md-12">
                <div class="form-group">
                  <label class="form-control-label" for="input-GitHub">GitHub網址</label>
                  <%= f.text_field :github, :class => "form-control form-control-alternative", :id => "input-GitHub", :placeholder => "請輸入GitHub網址" %>
                </div>
              </div>
              <div class="col-md-12">
                <div class="form-group">
                  <label class="form-control-label" for="input-Twitter">Twitter網址</label>
                  <%= f.text_field :twitter, :class => "form-control form-control-alternative", :id => "input-Twitter", :placeholder => "請輸入Twitter網址" %>
                </div>
              </div>
              <div class="col-md-12">
                <div class="form-group">
                  <label class="form-control-label" for="input-Instagram">Instagram網址</label>
                  <%= f.text_field :instagram, :class => "form-control form-control-alternative", :id => "input-Instagram", :placeholder => "請輸入Instagram網址" %>
                </div>
              </div>
              <div class="col-md-12">
                <div class="form-group">
                  <label class="form-control-label" for="input-address">封面照片 (檔案不可超過20M)</label>
                  <%= f.file_field :header_image, :class => "form-control form-control-alternative", :id => "input-image", :placeholder => "封面照片" %>
                </div>
              </div>
              <div class="col-md-12">
                <div class="form-group">
                  <label class="form-control-label" for="input-address">個人照 (800x800為最佳, 檔案不可超過20M)</label>
                  <%= f.file_field :image, :class => "form-control form-control-alternative", :id => "input-header_image", :placeholder => "個人照" %>
                </div>
              </div>
            </div>
          </div>
          <hr class="my-4" />
          <!-- Description -->
          <h6 class="heading-small text-muted mb-4">關於我</h6>
          <div class="pl-lg-4">
            <div class="form-group">
              <%= f.text_area :about, :class => "form-control form-control-alternative", :rows => "8", :placeholder => "關於我...", :required => "required" %>
            </div>
            <%= f.submit :class => "btn btn-primary", :value => "儲存" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<%# form_for @user do |user| %>
  <!-- <p> -->
    <%# user.label :email %>
    <%# user.text_field :email %>
  <!-- </p>
  <p> -->
    <%# user.label :password %>
    <%# user.password_field :password %>
  <!-- </p>
  <p> -->
    <%# user.label :password_confirmation %>
    <%# user.password_field :password_confirmation %>
  <!-- </p> -->
  <!-- <p class="button"><%# user.submit %></p> -->
<%# end %>

<div class="main-content">
  <!-- Navbar -->
  <nav class="navbar navbar-top navbar-horizontal navbar-expand-md navbar-dark">
    <div class="container px-4">
      <a class="navbar-brand" href="../index.html">
        <%= image_tag "qwq.png" %>
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar-collapse-main" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbar-collapse-main">
        <!-- Collapse header -->
        <div class="navbar-collapse-header d-md-none">
          <div class="row">
            <div class="col-6 collapse-brand">
              <%= link_to root_path do %>
                <%= image_tag "qwq.png" %>
              <% end %>
            </div>
            <div class="col-6 collapse-close">
              <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbar-collapse-main" aria-controls="sidenav-main" aria-expanded="false" aria-label="Toggle sidenav">
                <span></span>
                <span></span>
              </button>
            </div>
          </div>
        </div>
          <!-- Navbar items -->
          <!-- <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <a class="nav-link nav-link-icon" href="../index.html">
                <i class="ni ni-planet"></i>
                <span class="nav-link-inner--text">Dashboard</span>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link nav-link-icon" href="../examples/register.html">
                <i class="ni ni-circle-08"></i>
                <span class="nav-link-inner--text">Register</span>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link nav-link-icon" href="../examples/login.html">
                <i class="ni ni-key-25"></i>
                <span class="nav-link-inner--text">Login</span>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link nav-link-icon" href="../examples/profile.html">
                <i class="ni ni-single-02"></i>
                <span class="nav-link-inner--text">Profile</span>
              </a>
            </li>
          </ul> -->
      </div>
    </div>
  </nav>
  <!-- Header -->
  <div class="header bg-gradient-primary py-7 py-lg-8">
    <div class="container">
      <div class="header-body text-center mb-7">
        <div class="row justify-content-center">
          <div class="col-lg-5 col-md-6">
            <h1 class="text-white">歡 迎</h1>
            <p class="text-lead text-light">這 裡 是 QAQ の Blog</p>
          </div>
        </div>
      </div>
    </div>
    <div class="separator separator-bottom separator-skew zindex-100">
      <svg x="0" y="0" viewBox="0 0 2560 100" preserveAspectRatio="none" version="1.1" xmlns="http://www.w3.org/2000/svg">
        <polygon class="fill-default" points="2560 0 2560 100 0 100"></polygon>
      </svg>
    </div>
  </div>
  <!-- Page content -->
  <div class="container mt--8 pb-5">
    <!-- Table -->
    <div class="row justify-content-center">
      <div class="col-lg-6 col-md-8">
        <div class="card bg-secondary shadow border-0">
          <div class="card-header bg-transparent pb-5">
            <div class="text-muted text-center mt-2 mb-4"><small>Sign up with</small></div>
            <div class="text-center">
              <a href="#" class="btn btn-neutral btn-icon mr-4">
                <span class="btn-inner--icon"><i class="fab fa-github"></i></span>
                <span class="btn-inner--text">Github</span>
              </a>
              <a href="#" class="btn btn-neutral btn-icon">
                <span class="btn-inner--icon"><i class="fab fa-google"></i></span>
                <span class="btn-inner--text">Google</span>
              </a>
            </div>
          </div>
          <div class="card-body px-lg-5 py-lg-5">
            <div class="text-center text-muted mb-4">
              <small><%= link_to "登入", sign_in_path %></small><br>
              <script>
                <% if flash[:alert].present? %>
                  swal ( "噢..不..." , "<%= flash[:alert] %>",  "error" )
                <% end %>
              </script>
              <small><%= flash[:alert] %></small>
            </div>
            <%= form_for @user, :html => {:role => "form"} do |user| %>
              <div class="form-group">
                <div class="input-group input-group-alternative mb-3">
                  <div class="input-group-prepend">
                    <span class="input-group-text"><i class="fas fa-user"></i></span>
                  </div>
                  <%= user.text_field :username, :class => "form-control", :placeholder => "帳號", :required => "required" %>
                  <!-- <input class="form-control" placeholder="Name" type="text"> -->
                </div>
              </div>
              <div class="form-group">
                <div class="input-group input-group-alternative mb-3">
                  <div class="input-group-prepend">
                    <span class="input-group-text"><i class="fas fa-envelope"></i></span>
                  </div>
                  <%= user.email_field :email, :class => "form-control", :placeholder => "E-mail", :required => "required" %>
                </div>
              </div>
              <div class="form-group">
                <div class="input-group input-group-alternative mb-3">
                  <div class="input-group-prepend">
                    <span class="input-group-text"><i class="fas fa-key"></i></span>
                  </div>
                  <%= user.password_field :password, :class => "form-control", :placeholder => "密碼", :required => "required" %>
                </div>
              </div>
              <div class="form-group">
                <div class="input-group input-group-alternative">
                  <div class="input-group-prepend">
                    <span class="input-group-text"><i class="fas fa-key"></i></span>
                  </div>
                  <%= user.password_field :password_confirmation, :class => "form-control", :placeholder => "確認密碼", :required => "required" %>
                </div>
              </div>
                <!-- <div class="text-muted font-italic"><small>password strength: <span class="text-success font-weight-700">strong</span></small></div> -->
              <div class="row my-4">
                <div class="col-12">
                    <!-- <div class="custom-control custom-control-alternative custom-checkbox">
                      <input class="custom-control-input" id="customCheckRegister" type="checkbox">
                      <label class="custom-control-label" for="customCheckRegister">
                        <span class="text-muted">我同意 <a href="#!">Privacy Policy</a></span>
                      </label>
                    </div> -->
                </div>
              </div>
              <div class="text-center">
                <%= user.submit "建立" , :class => "btn btn-primary mt-4" %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- Footer -->
<footer class="py-5">
  <div class="container">
    <div class="row align-items-center justify-content-xl-between">
      <div class="col-xl-12">
        <div class="col-xl-12 text-muted" style="font-size: 1em; padding-top:40px;">
          <center>
            Copyrights © 2018 Alan. All Rights Reserved.
          </center>
        </div>
      </div>
    </div>
  </div>
</footer>

app/views/users/show.html.erb
<div class="row">

  <div class="col-xl-1 order-xl-1" >
  </div>

  <div class="col-xl-10 order-xl-1" >
    <div class="card card-profile shadow" >
      <div class="card-profile-image">
        <% if @userInformation.image.present? %>
          <%= image_tag @userInformation.image_url, :class => "rounded-circle" %>
        <% else %>
          <%= image_tag "penguin.jpg", :class => "rounded-circle" %>
        <% end %>
      </div>
      <div class="card-header text-center border-0 pt-8 pt-md-4 pb-0 pb-md-4">
        <div class="d-flex justify-content-between">
        </div>
      </div>
      <div class="card-body pt-0 pt-md-4">
        <div class="row">
          <div class="col">
            <div class="card-profile-stats d-flex justify-content-center mt-md-5">
              <div>
                <span class="heading"><%= @article_size %></span>
                <span class="description">文章</span>
              </div>
              <div>
                <% if @userInformation.email.blank? %>
                  <i class="far fa-3x fa-envelope blank_email"></i>
                <% else %>
                  <%= mail_to @userInformation.email do %>
                    <i class="far fa-3x fa-envelope"></i>
                  <% end %>
                <% end %>
              </div>
              <div>
                <% if @userInformation.twitter.blank? %>
                  <i class="fab fa-3x fa-twitter blank_twitter"></i>
                <% else %>
                  <%= link_to @userInformation.twitter, :target => "_blank" do %>
                    <i class="fab fa-3x fa-twitter"></i>
                  <% end %>
                <% end %>
              </div>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col">
            <div class="card-profile-stats d-flex justify-content-center " style="margin-top:-30px">  <!--增加與上方距離 mt-md-5 -->
              <div>
                <% if @userInformation.github.blank? %>
                  <i class="fab fa-3x fa-github blank_github"></i>
                <% else %>
                  <%= link_to @userInformation.github, :target => "_blank" do %>
                    <i class="fab fa-3x fa-github"></i>
                  <% end %>
                <% end %>
              </div>
              <div>
                <% if @userInformation.facebook.blank? %>
                  <i class="fab fa-3x fa-facebook blank_facebook"></i>
                <% else %>
                  <%= link_to @userInformation.facebook, :target => "_blank" do %>
                    <i class="fab fa-3x fa-facebook-square"></i>
                  <% end %>
                <% end %>
              </div>
              <div>
                <% if @userInformation.instagram.blank? %>
                  <i class="fab fa-3x fa-instagram blank_instagram"></i>
                <% else %>
                  <%= link_to @userInformation.instagram, :target => "_blank" do %>
                    <i class="fab fa-3x fa-instagram"></i>
                  <% end %>
                <% end %>
              </div>
            </div>
          </div>
        </div>
        <div class="text-center">
          <h2>
            <%= @userInformation.name if @userInformation.name.present? %>
          </h2>
          <div class="h5 font-weight-300">
            <i class="ni location_pin mr-2"></i>
            <span class="font-weight-light">
              <%= @userInformation.birthday if @userInformation.birthday.present? %>
            </span>
          </div>
          <!-- <div class="h5 mt-4">
            <i class="ni business_briefcase-24 mr-2"></i>學生
          </div> -->
          <div>
            <i class="ni education_hat mr-2"></i>
            <%= @userInformation.school if @userInformation.school.present? %>
          </div>
          <hr class="my-4" />
          <p>
            <% if @userInformation.about.present? %>
              <%= simple_format(@userInformation.about) %>
            <% else %>
              <%= "這個人很懶，什麼東西都沒有留下..."%>
            <% end %>
          </p>
        </div>
      </div>
    </div>
  </div>

  <div class="col-xl-1 order-xl-2 mb-5 mb-xl-0" >
  </div>

</div>