config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  get 'sign_up' => "users#new"
  root "signin#index"
  get 'sign_in' => "signin#index"
  post "sign_in" => "signin#create"
  get "sign_out" => "signin#destroy"

  resources :users, :path => '' do
    resources :contexts
  end



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/context_controller.rb
class ContextController < ApplicationController

  LIMIT_PAGE = 5
  
  def index
    @articles = Article.all
    @first_page = 1
    if(@articles.count % LIMIT_PAGE != 0)
      @last_page = ( @articles.count / LIMIT_PAGE ) + 1
    else
      @last_page = ( @articles.count / LIMIT_PAGE )
    end

    if params[:page]
      @page = params[:page].to_i
    else
      @page = 1
    end

    @poii = []
    @articles.each do |article|
      @poii << [article.id, article.title]
    end
#        限制筆數
    @articles = @articles.offset( ((@page - 1) * LIMIT_PAGE) ).limit(LIMIT_PAGE)
  end

end

app/controllers/contexts_controller.rb
class ContextsController < ApplicationController
  before_action :is_public_private, only: [:index, :new, :create, :show, :edit, :update, :destroy]
  LIMIT_PAGE = 5

  def index
    if @public_page_user.nil?
      # 網址資料錯誤
      redirect_to root_path
    else
      # header_image
      @userInformation = UsersInformation.find_by_user_id(@public_page_user.id)
      @page_title = @userInformation.name
      # 文章
      if params[:search_title].blank?
        @articles = Article.where(:user_id => @public_page_user.id )
      elsif params[:search_title].present?
        @articles = Article.search_title(@public_page_user.id, "%#{params[:search_title]}%")
      end

      if session[:user_id].nil?
        # 未登入
      else
        # 已登入
        if @public_page_user.id != session[:user_id]
          # 登入訪問別人
        elsif @public_page_user.id == session[:user_id]
          # 登入訪問自己
          @public_page_user = nil
        end
      end
      # 分頁
      @first_page = 1
      if(@articles.count % LIMIT_PAGE != 0)
        @last_page = ( @articles.count / LIMIT_PAGE ) + 1
      else
        @last_page = ( @articles.count / LIMIT_PAGE )
      end
      if params[:page]
        @page = params[:page].to_i
      else
        @page = 1
      end
      # 限制筆數
      @articles = @articles.offset( ((@page - 1) * LIMIT_PAGE) ).limit(LIMIT_PAGE)
    end
    # puts "123"
    # puts session[:user_id].present?
    # puts "---"
    #
    # @re = Article.where(:user_id => session[:user_id])
    # @re.each do |uu|
    #   puts uu.title
    # end
    #
    # puts "---"
    # @c8 = Article.find_by_sql("select * from articles where user_id = '#{session[:user_id]}' ")
    # @c8.each do |oo|
    #   puts oo.title
    # end

    # @ppa = Article.where(:user_id => params[:user_id])
    # puts @ppa.first.title

    # @searchs = []
    # @articles.each do |article|
    #   @searchs << [article.id, article.title]
    # end
  end

  def new
    if @public_page_user.nil?
      # 網址資料錯誤
      redirect_to root_path
    else
      if session[:user_id].nil?
        # 未登入
        redirect_to root_path
      else
        # 已登入
        if @public_page_user.id != session[:user_id]
          # 登入訪問別人
          #這篇違章不是你的
          redirect_to root_path
        elsif @public_page_user.id == session[:user_id]
          # 登入訪問自己
          #header_image
          @userInformation = UsersInformation.find_by_user_id(session[:user_id])
          @public_page_user = nil
          @article = Article.new
        else
          redirect_to root_path
        end
      end
    end
  end

  def create
    if @public_page_user.nil?
      # 網址資料錯誤
      redirect_to root_path
    else
      if session[:user_id].nil?
        # 未登入
        redirect_to root_path
      else
        # 已登入
        if @public_page_user.id != session[:user_id]
          # 登入訪問別人
          #這篇文章不是你的
          redirect_to root_path
        elsif @public_page_user.id == session[:user_id]
          # 登入訪問自己
          #header_image
          @userInformation = UsersInformation.find_by_user_id(session[:user_id])
          @public_page_user = nil
          @Article = Article.new(context_params)
          @Article.pentime = Time.zone.now
          @Article.user_id = session[:user_id]
          if @Article.save
            redirect_to user_context_path(@private_page_user.username, @Article.slug)
          else
            flash.now.alert = "新增失敗"
            render "new"
          end
        end
      end
    end
  end

  def show
    if @public_page_user.nil?
      # 網址資料錯誤
      redirect_to root_path
    else
      #header_image
      @userInformation = UsersInformation.find_by_user_id(@public_page_user.id)
      @article = Article.friendly.find_by_user_id_and_slug(@public_page_user.id ,params[:id])
      if @article.nil?
        redirect_to root_path
      else
        # @previous = Article.where("user_id = ? and id < ? ", @public_page_user.id, @article.id).order(:id).last
        @previous = Article.back_page(@public_page_user.id, @article.id, :id)
        # @next = Article.where("user_id = ? and id > ?", @public_page_user.id, @article.id).order(:id).first
        @next = Article.next_page(@public_page_user.id, @article.id, :id)
        if session[:user_id].nil?
          # 未登入
        else
          # 已登入
          if @public_page_user.id != session[:user_id]
            # 登入訪問別人
          elsif @public_page_user.id == session[:user_id]
            # 登入訪問自己
            @public_page_user = nil
          end
        end
      end
    end
  end

  def edit
    if @public_page_user.nil?
      # 網址資料錯誤
      redirect_to root_path
    else
      if session[:user_id].nil?
        # 未登入
        redirect_to root_path
      else
        # 已登入
        if @public_page_user.id != session[:user_id]
          # 登入訪問別人
          #這篇違章不是你的
          redirect_to root_path
        elsif @public_page_user.id == session[:user_id]
          # 登入訪問自己
          #header_image
          @userInformation = UsersInformation.find_by_user_id(session[:user_id])
          @public_page_user = nil
          @article = Article.friendly.find_by_user_id_and_slug(session[:user_id], params[:id])
          if @article.nil?
            #你沒有這篇文章
            redirect_to root_path
          end
        end
      end
    end
  end

  def update
    if @public_page_user.nil?
      # 網址資料錯誤
      redirect_to root_path
    else
      # 已登入
      if @public_page_user.id != session[:user_id]
        # 登入訪問別人
        # 這篇文章不是你的
        redirect_to root_path
      elsif @public_page_user.id == session[:user_id]
        # 登入訪問自己
        @public_page_user = nil
        @article = Article.friendly.find_by_user_id_and_slug(session[:user_id], params[:id])
        if @article.update(context_params)
          redirect_to user_context_path(@private_page_user.username, @article.slug)
        else
          flash.now.alert = "修改失敗"
          render :edit
        end
      end
    end
  end

  def destroy
    if @public_page_user.nil?
      # 網址資料錯誤
      redirect_to root_path
    else
      # 已登入
      if @public_page_user.id != session[:user_id]
        # 登入訪問別人
        # 這篇文章不是你的
        redirect_to root_path
      elsif @public_page_user.id == session[:user_id]
        # 登入訪問自己
        @public_page_user = nil
        @article = Article.friendly.find_by_user_id_and_slug(session[:user_id], params[:id])
        @article.destroy if @article
        redirect_to user_contexts_path(@private_page_user.username), :notice => "刪除成功"
      end
    end
  end

  private
  def context_params
      params.require(:article).permit(:title, :author, :tag, :image, :context )
  end

  def is_public_private
    @public_page_user = User.find_by_username(params[:user_id])
    @private_page_user = User.find_by_id(session[:user_id])
    if @public_page_user.present?
      @common＿lock = @public_page_user
    else
      @common＿lock = @private_page_user
    end
  end

end

app/helpers/contexts_helper.rb
module ContextsHelper
end

app/views/contexts/_old_file/_old_index.html.erb
<div class="row">
  <div class="col-2"></div>
    <div class="col-8 col-sm-6">
      <% @articles.each do |article| %>
        <article>
          <div style="word-wrap: break-word; word-break: normal; height: 100%;">
            <div id="article-title-font-size" ><a href="#"><%= article.title %></a></div>
            <span class="text-muted"><%# article.pentime.strftime("%Y-%m-%d %A") %></span><br/>
            <a href="#" class="text-success"><%= article.tag %></a><br/>
            <%= article.id %>
            <spin><%= link_to "continue read", user_context_path(params[:user_id] ,article.id) %></spin>
          </div>
          <div style="margin-top: 9px">
            <% if current_user %>
              <% if session[:user_id] == @user.id %>
                <%= link_to "edit", edit_user_context_path(params[:user_id], article.id) %>
              <% end %>
            <% end %>
          </div>
        </article>
      <% end %>

    <div class="row" id="divpage">
      <div aria-label="Page navigation example" >
        <ul class="pagination">
          <% if @page > @first_page %>
            <li class="page-item">
              <%= link_to root_path(page: @page - 1), :class => "page-link", "aria-label" => "Previous" do %>
                <span aria-hidden="true">&laquo;</span>
                <span class="sr-only">Previous</span>
              <% end %>
            </li>
          <% end %>
          <% (@first_page..@last_page).each do |page_number| %>
            <li class="page-item"><%= link_to page_number, root_path(page: page_number), :class => "page-link" %></li>
          <% end %>
          <% if @page < @last_page %>
            <li class="page-item">
              <%= link_to root_path(page: @page + 1), :class => "page-link", :"aria-label" => "Next" do %>
<!--                      <a class="page-link" href="#" aria-label="Next">-->
                <span aria-hidden="true">&raquo;</span>
                <span class="sr-only">Next</span>
<!--                      </a>-->
              <% end %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
  <div class="col-2 col-sm-4">
    <div class="input-group mb-3" style="margin-top:10px;" id="searchbutton">
      <input type="text" class="form-control" placeholder="Search" aria-label="Search" aria-describedby="button-addon2" id="tags">
      <div class="input-group-append">
                  <%= link_to "送出", "#", :class => "btn btn-outline-secondary", :style => "background-color:white;", :id =>"button-addon2" %>
<!--                <button class="btn btn-outline-secondary" type="button" id="button-addon2" style="background-color:white;" >submit</button>-->
      </div>
    </div>
  </div>
</div>

<script>
    //搜尋功能
    var search_title = [];
    var search_id = [];
    <% @searchs.each do |search| %>
        search_title.push( "<%= search[1] %>" );
        search_id.push( "<%= search[0] %>" );
    <% end %>
    $( "#tags" ).autocomplete({
      source: search_title
    });
    $("#button-addon2").click(function(){
        for(var i = 0; i < search_title.length; i++){
            if( $("#tags").val() == search_title[i]){
                $("a").attr("href", "/contexts/" + search_id[i])
            }
        }
    });
</script>

app/views/contexts/_old_file/_old_show.html.erb
<style>
    header {
        display: none;
    }
    main {
        background: white;
    }
</style>

<div class="row">
    <div class="col-2"></div>
    <div class="col-7">
        <div class="row">
            <div class="col-12">
            <center>
                <%= @article.title %><br/>
                <%= @article.tag %><br/>
                <%# @article.pentime.strftime("%Y-%m-%d %A") %><br/>
                <%# @article.pentime.strftime("%H:%M") %><br/>
            </center>
                <p>
                  <%= h(@article.context).gsub("\n", "<br>").html_safe %>
                </p>
                <div class="row">
                    <div class="pagination col-1">
                        <% if @previous != nil %>
                            <div class="page-item">
                                <%= link_to "Previous", user_context_path(params[:user_id], @previous), :class => "page-link" %>
                            </div>
                        <% end %>
                    </div>
                    <div class="col-10">
                    </div>
                    <div class="pagination col-1">
                      <% if @next != nil %>
                        <div class="page-item">
                            <%= link_to "Next", user_context_path(params[:user_id], @next), :class => "page-link" %>
                        </div>
                      <% end %>
                    </div>
                </div>
            </div>

        </div>
        <div id="disqus_thread"></div>
        <script>
            var disqus_config = function () {
              this.language = "zh_TW";
            };
        (function() { // DON'T EDIT BELOW THIS LINE
        var d = document, s = d.createElement('script');
        s.src = 'https://my-ykurey.disqus.com/embed.js';
        s.setAttribute('data-timestamp', +new Date());
        (d.head || d.body).appendChild(s);
        })();
        </script>
        <noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
    </div>

    <div class="col-3"></div>
</div>