config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  get 'sign_up' => "users#new"
  root "signin#index"
  get 'sign_in' => "signin#index"
  post "sign_in" => "signin#create"
  get "sign_out" => "signin#destroy"

  resources :users, :path => '' do
    resources :contexts
  end



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/signin_controller.rb
class SigninController < ApplicationController
  layout "log_in"

  def index
    @page_title = "登入"
    if session[:user_id] != nil
      user_username = User.find_by_id(session[:user_id]).username
      redirect_to edit_user_path(user_username)
    end
  end

  def create
    @page_title = "登入"
    user = User.authenticate(params[:username], params[:password])
    if user
      session[:user_id] = user.id
      user_username = User.find_by_id(user.id).username
      # redirect_to user_path(user_email), :notice => "登入成功"
      redirect_to edit_user_path(user_username)
    else
      flash.now.alert = "帳號或密碼錯誤"
      render "index"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, :notice => "登出成功!"
  end
end

app/controllers/signins_controller.rb
class SigninsController < ApplicationController

  layout "login"

  def index

  end

  def create
    user = User.authenticate(params[:username], params[:password])
    if user
      session[:user_id] = user.id
      user_username = User.find_by_id(user.id).username
      # redirect_to user_path(user_email), :notice => "登入成功"
      redirect_to edit_user_path(user_username)
    else
      flash.now.alert = "帳號或密碼錯誤"
      render "index"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, :notice => "登出成功!"
  end

end

app/helpers/signin_helper.rb
module SigninHelper
end

app/views/signin/index.html.erb
<%# form_tag signins_path do %>

  <!-- <p> -->
    <%# label_tag :email %>
    <%# text_field_tag :email %>
  <!-- </p> -->
  <!-- <p> -->
    <%# label_tag :password %>
    <%# password_field_tag :password %>
  <!-- </p> -->
  <!-- <p class="button"><%# submit_tag "Log in" %></p> -->
<%# end %>
<div class="main-content">
  <!-- Navbar -->
  <nav class="navbar navbar-top navbar-horizontal navbar-expand-md navbar-dark">
    <div class="container px-4">
      <a class="navbar-brand" href="../index.html">
        <%= image_tag "qwq.png" %>
        <!-- <img src="../assets/img/brand/white.png" /> -->
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar-collapse-main" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbar-collapse-main">
        <!-- Collapse header -->
        <div class="navbar-collapse-header d-md-none">
          <div class="row">
            <div class="col-6 collapse-brand">
              <%= link_to root_path do %>
                <%= image_tag "qwq.png" %>
              <% end %>
            </div>
            <div class="col-6 collapse-close">
              <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbar-collapse-main" aria-controls="sidenav-main" aria-expanded="false" aria-label="Toggle sidenav">
                <span></span>
                <span></span>
              </button>
            </div>
          </div>
        </div>
        <!-- Navbar items -->
        <!-- <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link nav-link-icon" href="../index.html">
              <i class="ni ni-planet"></i>
              <span class="nav-link-inner--text">登入</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link nav-link-icon" href="../examples/register.html">
              <i class="ni ni-circle-08"></i>
              <span class="nav-link-inner--text">註冊</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link nav-link-icon" href="../examples/login.html">
              <i class="ni ni-key-25"></i>
              <span class="nav-link-inner--text">個人頁面</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link nav-link-icon" href="../examples/profile.html">
              <i class="ni ni-single-02"></i>
              <span class="nav-link-inner--text">文章</span>
            </a>
          </li>
        </ul> -->
      </div>
    </div>
  </nav>
  <!-- Header -->
  <div class="header bg-gradient-primary py-7 py-lg-8">
    <div class="container">
      <div class="header-body text-center mb-7">
        <div class="row justify-content-center">
          <div class="col-lg-5 col-md-6">
            <h1 class="text-white">歡 迎</h1>
            <p class="text-lead text-light">這 裡 是 QAQ の Blog</p>
          </div>
        </div>
      </div>
    </div>
    <div class="separator separator-bottom separator-skew zindex-100">
      <svg x="0" y="0" viewBox="0 0 2560 100" preserveAspectRatio="none" version="1.1" xmlns="http://www.w3.org/2000/svg">
        <polygon class="fill-default" points="2560 0 2560 100 0 100"></polygon>
      </svg>
    </div>
  </div>
  <!-- Page content -->
  <div class="container mt--8 pb-5">
    <div class="row justify-content-center">
      <div class="col-lg-5 col-md-7">
        <div class="card bg-secondary shadow border-0">
          <div class="card-header bg-transparent pb-5">
            <div class="text-muted text-center mt-2 mb-3"><small>Sign in with</small></div>
            <div class="btn-wrapper text-center">
              <a href="#" class="btn btn-neutral btn-icon">
                <span class="btn-inner--icon"><i class="fab fa-github"></i></span>
                <span class="btn-inner--text">Github</span>
              </a>
              <a href="#" class="btn btn-neutral btn-icon">
                <span class="btn-inner--icon"><i class="fab fa-google"></i></span>
                <span class="btn-inner--text">Google</span>
              </a>
            </div>
          </div>
          <div class="card-body px-lg-5 py-lg-5">
            <div class="text-center text-muted mb-4">
              <small><%= link_to "註冊", new_user_path %></small><br>
              <script>
                <% if flash[:alert].present? %>
                  swal ( "噢..不..." , "<%= flash[:alert] %>",  "error" )
                <% end %>
                <% if flash[:notice].present? %>
                  swal ( "YA~" , "<%= flash[:notice] %>",  "success" )
                <% end %>
              </script>
              <small><%= flash[:alert] %></small>
            </div>
            <%= form_tag sign_in_url, :role => "form" do %>
              <div class="form-group mb-3">
                <div class="input-group input-group-alternative">
                  <div class="input-group-prepend">
                    <span class="input-group-text"><i class="fas fa-user"></i></span>
                  </div>
                  <%= text_field_tag :username, "",:class => "form-control", :placeholder => "帳號" %>
                </div>
              </div>
              <div class="form-group">
                <div class="input-group input-group-alternative">
                  <div class="input-group-prepend">
                    <span class="input-group-text"><i class="fas fa-key"></i></span>
                  </div>
                  <%= password_field_tag :password, "",:class => "form-control", :placeholder => "密碼"%>
                </div>
              </div>
              <!-- <div class="custom-control custom-control-alternative custom-checkbox">
                <input class="custom-control-input" id=" customCheckLogin" type="checkbox">
                <label class="custom-control-label" for=" customCheckLogin">
                  <span class="text-muted">記住我</span>
                </label>
              </div> -->
              <div class="text-center">
                <%= submit_tag "登入", :class => "btn btn-primary my-4" %>
              </div>
            <% end %>
          </div>
        </div>
        <div class="row mt-3">
          <div class="col-6">
            <!-- <a href="#" class="text-light blank_password"> -->
              <small class="text-light blank_password">忘記密碼</small>
            <!-- </a> -->
          </div>
          <div class="col-6 text-right">
            <small><%= link_to "註冊", new_user_path, :class => "text-light" %></small>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- Footer -->
<footer class="py-5">
  <div class="container">
    <div class="row align-items-center justify-content-xl-between">
      <div class="col-xl-12">
        <div class="col-xl-12 text-muted" style="font-size: 1em; padding-top:40px;">
          <center>
            Copyrights © 2018 Alan. All Rights Reserved.
          </center>
        </div>
      </div>
    </div>
  </div>
</footer>