config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  get 'sign_up' => "users#new"
  root "signin#index"
  get 'sign_in' => "signin#index"
  post "sign_in" => "signin#create"
  get "sign_out" => "signin#destroy"

  resources :users, :path => '' do
    resources :contexts
  end



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_card.html.erb
<div id="card" >
    <div class="close_show">
        <span aria-hidden="true" class="close_about">&times;</span>
    </div>
    <%= image_tag "1.jpg" , :class => "show_my_pic" %>
    <span class="show_name">Alan</span>
    <span class="show_name">Birthday:0528</span>
    <span class="show_name">大學：靜宜大學資管系</span>
    <span class="show_name">Hello~</span>
</div>

app/views/layouts/_footer.html.erb
<!-- Footer -->
<footer class="py-5">
  <div class="container">
    <div class="row align-items-center justify-content-xl-between">
      <div class="col-xl-12">
        <div class="col-xl-12 text-muted" style="font-size: 1em; padding-top:40px;">
          <center>
            Copyrights © 2018 Alan. All Rights Reserved.
          </center>
        </div>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<style>
  #header_image {
    background-image:
    <% if @userInformation.header_image.present? %>
      url(<%= @userInformation.header_image %>);
    <% else %>
      url(<%= "/desk.png" %>)
    <% end %>
  }
</style>

<!-- Header -->
<div class="header pb-8 pt-5 pt-lg-8 d-flex align-items-center" id="header_image" style="min-height: 600px; background-size: cover; background-position: center top;">
  <!-- Mask -->
  <!-- <span class="mask bg-gradient-default opacity-8"></span> -->
  <!-- Header container -->
  <div class="container-fluid d-flex align-items-center">
    <div class="row">
      <div class="col-lg-7 col-md-10">
        <!-- <h1 class="display-2 text-white">Hello Jesse</h1> -->
        <!-- <p class="text-white mt-0 mb-5">This is your profile page. You can see the progress you've made with your work and manage your projects or assigned tasks</p> -->
        <!-- <a href="#!" class="btn btn-info">Edit profile</a> -->
      </div>
    </div>
  </div>
</div>

app/views/layouts/_nav.html.erb
  <!-- Sidenav -->
  <nav class="navbar navbar-vertical fixed-left navbar-expand-md navbar-light bg-white" id="sidenav-main">
    <div class="container-fluid">
      <!-- Toggler -->
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#sidenav-collapse-main" aria-controls="sidenav-main" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <!-- Brand -->
      <% if @public_page_user.present? %>
        <%= link_to user_contexts_path(@public_page_user.username), :class => "navbar-brand pt-0" do %>
          <%= image_tag "qwq.png", :class => "navbar-brand-img"%>
        <% end %>
      <% else %>
        <%= link_to user_contexts_path(@private_page_user.username), :class => "navbar-brand pt-0" do %>
          <%= image_tag "qwq.png", :class => "navbar-brand-img"%>
        <% end %>
      <% end %>
      <!-- User -->
      <ul class="nav align-items-center d-md-none">
        <li class="nav-item dropdown">
          <a class="nav-link nav-link-icon" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <i class="far fa-gem"></i>
          </a>
          <div class="dropdown-menu dropdown-menu-arrow dropdown-menu-right" aria-labelledby="navbar-default_dropdown_1">
            <% if @userInformation.github.present? %>
              <%= link_to @userInformation.github, :class => "dropdown-item", :target => "_blank" do %>
                <i class="fab fa-github"></i>
                GitHub
              <% end %>
            <% end %>
            <% if @userInformation.facebook.present? %>
              <%= link_to @userInformation.facebook, :class => "dropdown-item", :target => "_blank" do %>
                <i class="fab fa-facebook-square"></i>
                Facebook
              <% end %>
            <% end %>
            <% if @userInformation.instagram.present? %>
              <%= link_to @userInformation.instagram, :class => "dropdown-item", :target => "_blank" do %>
                <i class="fab fa-instagram"></i>
                Instagram
              <% end %>
            <% end %>
            <% if @userInformation.twitter.present? %>
              <%= link_to @userInformation.twitter, :class => "dropdown-item", :target => "_blank" do %>
                <i class="fab fa-twitter"></i>
                Twitter
              <% end %>
            <% end %>
            <% if @userInformation.email.present? %>
              <%= mail_to @userInformation.email, :class => "dropdown-item" do %>
                <i class="far fa-envelope"></i>
                E-mail
              <% end %>
            <% end %>
          </div>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <div class="media align-items-center">
              <span class="avatar avatar-sm rounded-circle">
                <% if @userInformation.image.present? %>
                  <%= image_tag @userInformation.image_url %>
                <% else %>
                  <%= image_tag "penguin.jpg" %>
                <% end %>
              </span>
            </div>
          </a>
          <div class="dropdown-menu dropdown-menu-arrow dropdown-menu-right">
            <div class=" dropdown-header noti-title">
              <h6 class="text-overflow m-0">歡迎!</h6>
            </div>
            <% if @public_page_user.present? %>
              <%= link_to user_path(@public_page_user.username), :class => "dropdown-item" do %>
                <i class="far fa-gem"></i>
                <span>關於我...</span>
              <% end %>
              <%= link_to user_contexts_path(@public_page_user.username), :class => "dropdown-item" do %>
                <i class="far fa-gem"></i>
                <span>文章總覽</span>
              <% end %>
            <% end %>
            <% if current_user && @public_page_user %>
              <div class="dropdown-divider"></div>
            <% end %>
            <% if current_user %>
              <%= link_to user_path(@private_page_user.username), :class => "dropdown-item" do %>
                <i class="far fa-gem"></i>
                <span>關於我...</span>
              <% end %>
              <%= link_to user_contexts_path(@private_page_user.username), :class => "dropdown-item" do %>
                <i class="far fa-gem"></i>
                <span>文章總覽</span>
              <% end %>
              <%= link_to edit_user_path(@private_page_user.username), :class => "dropdown-item" do %>
                <i class="far fa-gem"></i>
                <span>編輯關於我</span>
              <% end %>
              <%= link_to new_user_context_path(@private_page_user.username), :class => "dropdown-item" do %>
                <i class="far fa-gem"></i>
                <span>新增文章</span>
              <% end %>
              <%= link_to sign_out_path, :class => "dropdown-item" do %>
                <i class="far fa-gem"></i>
                登出
              <% end %>
            <% end %>
          </div>
        </li>
      </ul>
      <!-- Collapse -->
      <div class="collapse navbar-collapse" id="sidenav-collapse-main">
        <!-- Collapse header -->
        <div class="navbar-collapse-header d-md-none">
          <div class="row">
            <div class="col-6 collapse-brand">
              <% if @public_page_user.present? %>
                <%= link_to user_contexts_path(@public_page_user.username) do %>
                  <%= image_tag "qwq.png", :class => "navbar-brand-img"%>
                <% end %>
              <% else %>
                <%= link_to user_contexts_path(@private_page_user.username) do %>
                  <%= image_tag "qwq.png", :class => "navbar-brand-img"%>
                <% end %>
              <% end %>
            </div>
            <div class="col-6 collapse-close">
              <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#sidenav-collapse-main" aria-controls="sidenav-main" aria-expanded="false" aria-label="Toggle sidenav">
                <span></span>
                <span></span>
              </button>
            </div>
          </div>
        </div>
        <!-- Form -->
        <form class="mt-4 mb-3 d-md-none">
          <div class="input-group input-group-rounded input-group-merge">
            <input type="search" class="form-control form-control-rounded form-control-prepended" placeholder="Search" aria-label="Search">
            <div class="input-group-prepend">
              <div class="input-group-text">
                <span class="fa fa-search"></span>
              </div>
            </div>
          </div>
        </form>
        <% if @public_page_user.present? %>
          <ul class="navbar-nav">
            <li class="nav-item">
              <%= link_to user_path(@public_page_user.username), :class => "nav-link" do %>
                <i class="far fa-gem"></i>
                關於我...
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to user_contexts_path(@public_page_user.username), :class => "nav-link" do %>
                <i class="far fa-gem"></i>
                文章總覽
              <% end %>
            </li>
          </ul>
        <% end %>
        <% if current_user && @public_page_user %>
          <hr class="my-3">
        <% end %>
        <% if current_user %>
          <ul class="navbar-nav mb-md-3">
            <li class="nav-item">
                <%= link_to user_path(@private_page_user.username), :class => "nav-link" do %> <!--用do的話，前面就不是放名稱，直接往前一個格網址-->
                <i class="far fa-gem"></i>
                關於我...
                <% end %>
            </li>
            <li class="nav-item">
                <%= link_to user_contexts_path(@private_page_user.username), :class => "nav-link" do %>
                <i class="far fa-gem"></i>
                文章總覽
                <% end %>
            </li>
            <li class="nav-item">
                <%= link_to edit_user_path(@private_page_user.username), :class => "nav-link" do %>
                <i class="far fa-gem"></i>
                編輯關於我
                <% end %>
            </li>
            <li class="nav-item">
              <%= link_to new_user_context_path(@private_page_user.username), :class => "nav-link" do %>
                <i class="far fa-gem"></i>
                 新增文章
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to sign_out_path, :class => "nav-link" do %>
                <i class="far fa-gem"></i>
                登出
              <% end %>
            </li>
          </ul>
        <% end %>
      </div>
    </div>
  </nav>

app/views/layouts/_phone_nav.html.erb
<!-- Top navbar -->
<nav class="navbar navbar-top navbar-expand-md navbar-dark" id="navbar-main">
  <div class="container-fluid">
    <!-- Brand -->
    <%= link_to "回首頁", user_contexts_path(@common＿lock.username), :class => "h4 mb-0 text-white text-uppercase d-none d-lg-inline-block" %>
    <!-- Form -->
    <%= form_tag(user_contexts_path(@common＿lock.username), :method => "get", :class => "navbar-search navbar-search-dark form-inline mr-3 d-none d-md-flex ml-lg-auto") do %>
      <div class="form-group mb-0">
        <div class="input-group input-group-alternative">
          <div class="input-group-prepend">
            <span class="input-group-text"><i class="fas fa-search"></i></span>
          </div>
          <%# text_field_tag :search_title, "", :class => "form-control" %>
          <input class="form-control" placeholder="Search" type="text" name="search_title">
        </div>
      </div>
    <% end %>
    <!-- <form class="navbar-search navbar-search-dark form-inline mr-3 d-none d-md-flex ml-lg-auto">
      <div class="form-group mb-0">
        <div class="input-group input-group-alternative">
          <div class="input-group-prepend">
            <span class="input-group-text"><i class="fas fa-search"></i></span>
          </div>
          <input class="form-control" placeholder="Search" type="text">
        </div>
      </div>
    </form> -->
    <!-- User -->
    <ul class="navbar-nav align-items-center d-none d-md-flex">
      <li class="nav-item dropdown">
        <a class="nav-link pr-0" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <div class="media align-items-center">
            <span class="avatar avatar-sm rounded-circle">
              <% if @userInformation.image.present? %>
                <%= image_tag @userInformation.image_url %>
              <% else %>
                <%= image_tag "penguin.jpg" %>
              <% end %>
            </span>
            <div class="media-body ml-2 d-none d-lg-block">
              <span class="mb-0 text-sm  font-weight-bold"><%= @userInformation.name %></span>
            </div>
          </div>
        </a>
        <div class="dropdown-menu dropdown-menu-arrow dropdown-menu-right">
          <div class=" dropdown-header noti-title">
            <h6 class="text-overflow m-0">歡迎!</h6>
          </div>
          <% if @public_page_user.present? %>
            <%= link_to user_path(@public_page_user.username), :class => "dropdown-item" do %>
              <i class="far fa-gem"></i>
              <span>關於我...</span>
            <% end %>
            <%= link_to user_contexts_path(@public_page_user.username), :class => "dropdown-item" do %>
              <i class="far fa-gem"></i>
              <span>文章總覽</span>
            <% end %>
          <% end %>
          <% if current_user && @public_page_user %>
            <div class="dropdown-divider"></div>
          <% end %>
          <% if current_user %>
            <%= link_to user_path(@private_page_user.username), :class => "dropdown-item" do %>
              <i class="far fa-gem"></i>
              <span>關於我...</span>
            <% end %>
            <%= link_to user_contexts_path(@private_page_user.username), :class => "dropdown-item" do %>
              <i class="far fa-gem"></i>
              <span>文章總覽</span>
            <% end %>
            <%= link_to edit_user_path(@private_page_user.username), :class => "dropdown-item" do %>
              <i class="far fa-gem"></i>
              <span>編輯關於我</span>
            <% end %>
            <%= link_to new_user_context_path(@private_page_user.username), :class => "dropdown-item" do %>
              <i class="far fa-gem"></i>
              <span>新增文章</span>
            <% end %>
            <%= link_to sign_out_path, :class => "dropdown-item" do %>
              <i class="far fa-gem"></i>
              登出
            <% end %>
          <% end %>
        </div>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <% if @page_title.present? %>
      <title><%= @page_title + "のBlog" %></title>
    <% else %>
      <title><%= "QAQ のBlog" %></title>
    <% end %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta charset="utf-8">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
    <!-- <script defer src="https://use.fontawesome.com/releases/v5.7.2/js/all.js" integrity="sha384-0pzryjIRos8mFBWMzSSZApWtPl/5++eIfzYmTgBBmXYdhvxPc+XcFEk+zJwDgWbP" crossorigin="anonymous"></script> -->
  </head>

  <body >
    <%= render partial: 'layouts/nav' %>
    <!-- Main content -->
    <div class="main-content">
      <%= render partial: 'layouts/phone_nav' %>
      <%= render partial: 'layouts/header' %>
      <!-- Page content -->
      <div class="container-fluid mt--7">
        <%= yield %>
        <%= javascript_include_tag "application_footer" %>
        <!-- Footer -->
        <%= render partial: 'layouts/footer' %>
      </div>
    </div>
  </body>
</html>

app/views/layouts/log_in.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= "QAQのBlog の" + @page_title %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta charset="utf-8">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous"> -->
    <script defer src="https://use.fontawesome.com/releases/v5.7.2/js/all.js" integrity="sha384-0pzryjIRos8mFBWMzSSZApWtPl/5++eIfzYmTgBBmXYdhvxPc+XcFEk+zJwDgWbP" crossorigin="anonymous"></script>
  </head>

  <body class="bg-default">
    <%= yield %>
    <%= javascript_include_tag "application_footer" %>
  </body>
</html>

app/views/layouts/login.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Backstageykurey</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous"> -->
    <script defer src="https://use.fontawesome.com/releases/v5.7.2/js/all.js" integrity="sha384-0pzryjIRos8mFBWMzSSZApWtPl/5++eIfzYmTgBBmXYdhvxPc+XcFEk+zJwDgWbP" crossorigin="anonymous"></script>
  </head>

  <body class="bg-default">
    <%= yield %>
  </body>
</html>

app/views/layouts/old_application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>YkureyBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      <div class="main_part" >
          <nav>
             <%= render partial: 'layouts/nav' %>
          </nav>
          <div class="container-fluid">
              <main>
                  <header>
                      <%= render partial: 'layouts/header' %>
                      <% if current_user %>
                        您好：<%= current_user.email %>.<br>
                        <%= link_to "Log out", log_out_path %>
                      <% else %>
                        <%= link_to "Sign up", sign_up_path %> or
                        <%= link_to "log in", log_in_path %>
                      <% end %>
                      <% flash.each do |name, msg| %>
                        <%= content_tag :div, msg, :id => "flash_#{name}" %>
                      <% end %>
                  </header>
                  <%= yield %>
                  <footer>
                    <%= render partial: 'layouts/footer' %>
                  </footer>
              </main>
          </div>
      </div>
      <div class="show_about">
          <%= render partial: 'layouts/card' %>
      </div>
  </body>
</html>